#### Make sure all the libraries are installed

In [2]:
from keras.models import Sequential
from keras.layers import Dense
import numpy
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np
# fix random seed for reproducibility allows us to reproduce the same results over and over
numpy.random.seed(7)

C:\Users\cody\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


#### Load
#### Preview
#### Q0. 
What is our input and output?  
#### Q1. 
Why "0:8" in X and "8" in Y?   

In [3]:
# load pima indians dataset
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
print(dataset.shape)

(768, 9)


#### split into input (X) and output (Y) variables

In [4]:
XTRAIN = dataset[:700,0:8]
YTRAIN = dataset[:700,8]
XVALIDATION = dataset[700:,0:8]
YVALIDATION = dataset[700:,8]

In [5]:
print(XTRAIN.shape)
print(YTRAIN.shape)
print(XVALIDATION.shape)
print(YVALIDATION.shape)
print(XTRAIN[0:3,])
print(YTRAIN[0:3])
print(XVALIDATION[0:3,])
print(YVALIDATION[0:3])

(700, 8)
(700,)
(68, 8)
(68,)
[[  6.    148.     72.     35.      0.     33.6     0.627  50.   ]
 [  1.     85.     66.     29.      0.     26.6     0.351  31.   ]
 [  8.    183.     64.      0.      0.     23.3     0.672  32.   ]]
[1. 0. 1.]
[[  2.    122.     76.     27.    200.     35.9     0.483  26.   ]
 [  6.    125.     78.     31.      0.     27.6     0.565  49.   ]
 [  1.    168.     88.     29.      0.     35.      0.905  52.   ]]
[0. 1. 1.]


#### Q2. 
why is the input_dim 8? Can be replaced with X[0, :]


In [6]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 12)                108       
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________
None


#### Check for proper neural connections by compiling your model

In [7]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#### build the model with X and Y

In [24]:
# Fit the model
model.fit(X, Y, epochs=150, batch_size=10, validation_data = (XTRAIN, YTRAIN))

Train on 768 samples, validate on 700 samples
Epoch 1/150
768/768 [==============================] - 1s 1ms/step - loss: 3.6832 - acc: 0.5964 - val_loss: 1.2746 - val_acc: 0.5814
Epoch 2/150
768/768 [==============================] - 0s 177us/step - loss: 0.9286 - acc: 0.6003 - val_loss: 0.7848 - val_acc: 0.6471
Epoch 3/150
768/768 [==============================] - 0s 167us/step - loss: 0.7407 - acc: 0.6367 - val_loss: 0.7498 - val_acc: 0.6800
Epoch 4/150
768/768 [==============================] - 0s 177us/step - loss: 0.7082 - acc: 0.6615 - val_loss: 0.6721 - val_acc: 0.6486
Epoch 5/150
768/768 [==============================] - 0s 177us/step - loss: 0.6810 - acc: 0.6810 - val_loss: 0.6474 - val_acc: 0.6714
Epoch 6/150
768/768 [==============================] - 0s 172us/step - loss: 0.6505 - acc: 0.6836 - val_loss: 0.6408 - val_acc: 0.6671
Epoch 7/150
768/768 [==============================] - 0s 172us/step - loss: 0.6483 - acc: 0.6732 - val_loss: 0.6567 - val_acc: 0.6671
Epoch 8/150

Epoch 61/150
768/768 [==============================] - 0s 177us/step - loss: 0.5254 - acc: 0.7344 - val_loss: 0.5029 - val_acc: 0.7386
Epoch 62/150
768/768 [==============================] - 0s 172us/step - loss: 0.5169 - acc: 0.7565 - val_loss: 0.5201 - val_acc: 0.7357
Epoch 63/150
768/768 [==============================] - 0s 172us/step - loss: 0.5445 - acc: 0.7344 - val_loss: 0.4947 - val_acc: 0.7700
Epoch 64/150
768/768 [==============================] - 0s 177us/step - loss: 0.5318 - acc: 0.7396 - val_loss: 0.5166 - val_acc: 0.7557
Epoch 65/150
768/768 [==============================] - 0s 193us/step - loss: 0.5193 - acc: 0.7500 - val_loss: 0.4908 - val_acc: 0.7657
Epoch 66/150
768/768 [==============================] - 0s 172us/step - loss: 0.5066 - acc: 0.7500 - val_loss: 0.5009 - val_acc: 0.7457
Epoch 67/150
768/768 [==============================] - 0s 172us/step - loss: 0.5163 - acc: 0.7370 - val_loss: 0.4889 - val_acc: 0.7671
Epoch 68/150
768/768 [==========================

768/768 [==============================] - 0s 172us/step - loss: 0.4913 - acc: 0.7721 - val_loss: 0.4680 - val_acc: 0.7886
Epoch 122/150
768/768 [==============================] - 0s 172us/step - loss: 0.4816 - acc: 0.7799 - val_loss: 0.4882 - val_acc: 0.7743
Epoch 123/150
768/768 [==============================] - 0s 250us/step - loss: 0.4833 - acc: 0.7643 - val_loss: 0.4581 - val_acc: 0.7857
Epoch 124/150
768/768 [==============================] - 0s 219us/step - loss: 0.4841 - acc: 0.7786 - val_loss: 0.4628 - val_acc: 0.7929
Epoch 125/150
768/768 [==============================] - 0s 172us/step - loss: 0.4841 - acc: 0.7799 - val_loss: 0.4741 - val_acc: 0.7614
Epoch 126/150
768/768 [==============================] - 0s 177us/step - loss: 0.4784 - acc: 0.7682 - val_loss: 0.4642 - val_acc: 0.7771
Epoch 127/150
768/768 [==============================] - 0s 193us/step - loss: 0.4856 - acc: 0.7721 - val_loss: 0.4561 - val_acc: 0.7900
Epoch 128/150
768/768 [==============================] 

#### evaluate the model then visualize on the "Data we used the train the model itself"

In [26]:
# evaluate the model
scores = model.evaluate(XTRAIN, YTRAIN)

700/700 [==============================] - 0s 23us/step


In [27]:
print(model.metrics_names)
print(scores)

['loss', 'acc']
[0.47276437503950935, 0.7885714289120266]


In [28]:
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))


acc: 78.86%


#### Evaluate the model on the "Unknown" dataset (Validation Dataset)

In [29]:
scores = model.evaluate(XVALIDATION, YVALIDATION)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

68/68 [==============================] - 0s 59us/step

acc: 80.88%


An example of what the model has predicted and comparison with the true classes

In [35]:
print(XVALIDATION[0:5])
print(YVALIDATION[0:5])

[[2.00e+00 1.22e+02 7.60e+01 2.70e+01 2.00e+02 3.59e+01 4.83e-01 2.60e+01]
 [6.00e+00 1.25e+02 7.80e+01 3.10e+01 0.00e+00 2.76e+01 5.65e-01 4.90e+01]
 [1.00e+00 1.68e+02 8.80e+01 2.90e+01 0.00e+00 3.50e+01 9.05e-01 5.20e+01]
 [2.00e+00 1.29e+02 0.00e+00 0.00e+00 0.00e+00 3.85e+01 3.04e-01 4.10e+01]
 [4.00e+00 1.10e+02 7.60e+01 2.00e+01 1.00e+02 2.84e+01 1.18e-01 2.70e+01]]
[0. 1. 1. 0. 0.]


In [40]:
prediction = model.predict(XVALIDATION)

In [36]:
print(prediction[0:5])

[[0.37573642]
 [0.70850843]
 [0.8657279 ]
 [0.36483952]
 [0.2977636 ]]


In [37]:
print(prediction[0:5].round())

[[0.]
 [1.]
 [1.]
 [0.]
 [0.]]




## Accuracy is not sufficient to evaluate our model's ability to do binary classification  
-----------  
#### we will evaluate the model using precision and recall as well.

First we show the precision, recall and F1 score for our training set

#### First we show the precision, recall and F1 score for our training set

In [44]:
accuracy = accuracy_score(YVALIDATION, prediction.round())
precision = precision_score(YVALIDATION, prediction.round())
recall = recall_score(YVALIDATION, prediction.round())
f1score = f1_score(YVALIDATION, prediction.round())
print("Accuracy: %.2f%%" % (accuracy * 100.0))
print("Precision: %.2f%%" % (precision * 100.0))
print("Recall: %.2f%%" % (recall * 100.0))
print("F1-score: %.2f" % (f1score))

Accuracy: 80.88%
Precision: 79.17%
Recall: 70.37%
F1-score: 0.75
